### ISSUE TITLE
Api Access is disabled. Enable it in Account settings

### ISSUE THREAD

**Issue by ysilvela** [blockchain/api-v1-client-node#1]
I obtain this error when I try to get the balance of a new wallet recently created by the api.

The question is, It's needed provide manual access to all the wallets I create via API? Or a optional parameter  is needed during the creation call?

Thanks.

**Comment by jtormey** [comment]
When you create a new wallet with our api, api access is disabled by default in that wallet (which is why you are getting this error).

The solution to this issue is to include an api code as a parameter when creating a wallet. When a new wallet is created using an api code, future api requests containing that code will be allowed to access the wallet.

Documentation: https://blockchain.info/api/create_wallet
Request API code: https://blockchain.info/api/api_create_code

**Comment by ysilvela** [comment]
Hi Justin,

Sorry but not understand all you say. I pass the apicode to the
createWallet method.

Are you saying that the your api has an issue and is needed to include by
hand the apicode parameter in the url modifiying your code?

Thanks.

2015-06-30 15:50 GMT+02:00 Justin Tormey <notifications@github.com>:

**Comment by csancho** [comment]
Hi,
1º In Spanish
2º Translated to english
------------- Spanish -------------
Cuando trabajas con Blockchain es casi imprescindible generar tu propia iD de desarrollador, por decirlo así, se solicta en la siguiente url:
- https://blockchain.info/api/api_create_code
Cuando te envíen tu ID, algo parecida a esto: 50fff8df-4341-4fa4-a732-4ca454734541
Tienes que invocar la librería de Blockchain pasandole el api_code:
Antes: $Blockchain = new \Blockchain\Blockchain();
Despues: $Blockchain = new \Blockchain\Blockchain($my_api_code);
De esta forma puedes crear wallets y consultar blockchain sin problemas.
--------------English ------------
When you work with Blockchain is almost essential to generate your own developer ID, as it were at the following URL:
     - https://blockchain.info/api/api_create_code

When you send your ID, something like this: 50fff8df-4341-4fa4-a732-4ca454734541
You have to invoke the library by passing the api_code Blockchain:

Before: $ Blockchain = new \ Blockchain \ Blockchain ();
After: $ Blockchain = new \ Blockchain \ Blockchain ($my_api_code);

This way you can create and view wallets blockchain smoothly.
