### ISSUE TITLE
A mistake in MyWallet.prototype.send function

### ISSUE THREAD

**Issue by rattrap19** [blockchain/api-v1-client-node#12]
In MyWallet.prototype.send function (/MyWallet/index.js) at line 29 should be:
    params.to  = address;
not
    params.address = address;

When I tried to send btc using 'params.address' I failed, but when I changed it to 'params.to' I succeded.

Either there is a mistake or I don't understand something. Please check it. 
Thanks!

**Comment by jtormey** [comment]
Yeah, looks like that's a bug. I'll fix and release a patched version. Thanks for reporting!
