### ISSUE TITLE
Socket disconnects on inactivity

### ISSUE THREAD

**Issue by yangzai** [blockchain/api-v1-client-node#13]
Socket disconnects on inactivity of around 100 seconds. Current solution is to have an extra listen to onTransaction with empty callback. Perhaps ping method can be exposed from the websocket.

**Comment by susannaHayrapetyan** [comment]
Hi, 
I have the same problem, are there any solutions?

**Comment by jtormey** [comment]
To prevent the socket from closing, try pinging the socket on an interval like @yangzai suggested. You can do this using the `Socket.op` method (currently not documented):

```
let socket = new Socket()
setInterval(() => socket.op('ping'), 30000)
```

If that doesn't work, try listening for the `'close'` event and then reopening the socket when it's emitted.

**Comment by susannaHayrapetyan** [comment]
Reopening the socket works fine, thanks
