### ISSUE TITLE
Function for fetching historic ticker data

### ISSUE THREAD

**Issue by chovy** [blockchain/api-v1-client-node#15]
Is it possible to get the price of BTC/USD ticker on a given date in the past?

something like:

`
exchange.getTicker({ currency: 'BTC', date: '2015-01-01' });
`

**Comment by jtormey** [comment]
No, however we do have an endpoint that will convert a btc amount to a fiat value for a given time:
https://blockchain.info/frombtc?value=100000000&time=1463771173392&currency=USD

**Comment by chovy** [comment]
So the endpoint exists, but the module doesn't support it?

**Comment by jtormey** [comment]
Yeah, I'll look into adding it, but for now it seems like making the API call directly is the way to go.

**Comment by chovy** [comment]
ok cool. I'll take a look tonight -- if I can figure out I'll submit a PR.

**Comment by jtormey** [comment]
Yup, all times are GMT

**Comment by chovy** [comment]
Its odd that the transaction api gives you back time in seconds for an output but it looks like this api above needs time in ms so I can't just feed the output time into this api.

**Comment by jtormey** [comment]
Seems like a small an inconsistency in our API, multiplying by 1000 should work

**Comment by schnogz** [comment]
I have submitted a PR for this issue. Please review @jtormey :)

**Comment by jtormey** [comment]
Fixed by @schnogz in #22

**Comment by kenkit** [comment]
Why not just make it capable of extracting all the currencies at that given time.
It would be inefficient to be making multiple requests to get all other currencies

**Comment by jtormey** [comment]
If you call https://api.blockchain.info/ticker, you can get the current ticker prices for all currencies at once, but that endpoint doesn't support historical values.

**Comment by kenkit** [comment]
I was asking cause I need data for specific dates, the only thing that I see it will lead to is making multiple calls.

**Comment by jtormey** [comment]
Hmm, yeah, sorry we don't support pulling data for multiple currencies at a given date. It's something we would consider adding though, did you have a particular use case in mind?

**Comment by kenkit** [comment]
Yeah, I need data to train a model that will input bitcoin price data from specific dates to make a single prediction, the data will unfortunately include all the currencies currently available.
