### ISSUE TITLE
is quanity of transaction actual?

### ISSUE THREAD

**Issue by veitsi** [blockchain/api-v1-client-node#18]
hello, on the page https://github.com/blockchain/api-v1-client-node/tree/master/MyWallet
 it is written that minimal transaction is 0.005btc, but this sum is big enough, is it actual now?

**Comment by jtormey** [comment]
This minimum is only needed if you're including a public note with the transaction.
To prevent spamming, all outputs must be > 0.005, not just the sent amount (this includes the change output).
