### ISSUE TITLE
Optimal fee estimate available?

### ISSUE THREAD

**Issue by jonathancross** [blockchain/api-v1-client-node#19]
Is there a way to query the API for the current optimal mining fee per 1000 bytes in order to have transaction accepted into next block?

In Bitcoin Core this would be: `bitcoin-cli estimatefee 1`

**Comment by jtormey** [comment]
It's not currently implemented in this API, but you can get this information through our http API: https://api.blockchain.info/fees

In the response, the `fee` property first estimate (`estimates[0]`) is the recommended fee per kb for inclusion in the next block.

**Comment by jonathancross** [comment]
Thanks @jtormey!  Is there a way to reach this via the Tor hidden service?
For some reason https://blockchainbdgpzk.onion/fees fails while other endpoints work just fine.  (eg https://blockchainbdgpzk.onion/latestblock)
