### ISSUE TITLE
The Function getChartData(chart, options) Don't Recognize The Options

### ISSUE THREAD

**Issue by Tubaleviao** [blockchain/api-v1-client-node#20]
I'm calling the function like this: 
`var p = statistics.getChartData("market-price", {'timespan': 'all'});`
It should return the values from all dates, but isn't working [(like this).](https://blockchain.info/pt/charts/market-price?timespan=all)
Am I doing it right? I need help, the readme doesn't explain the options parameter.

**Comment by jtormey** [comment]
Right now the library doesn't support a 'timespan' option. I'll look into adding it, pull requests are always welcome too (if you need this functionality asap).
