### ISSUE TITLE
Ws library needs to be updated

### ISSUE THREAD

**Issue by schnogz** [blockchain/api-v1-client-node#25]
I have ran into this `RangeError: out of range index` Websocket [issue](https://github.com/websockets/ws/issues/778) numerous times while developing using the socket based features of this library and Node v6.x.  It appears to be a bug in ws@0.8 and Node 6.x.  

Upgrading to ws@[1.1.2](https://github.com/websockets/ws/releases/tag/1.1.2) fixes this issue and from my testing causes no issues with this library. There are no release notes from 0.x to 1.x that indicate breaking changes.

I looked into an upgrade straight to ws@[2.0](https://github.com/websockets/ws/releases/tag/2.0.0) but the laundry list of breaking changes seems daunting to vet.

**Comment by jtormey** [comment]
Thanks!
