### ISSUE TITLE
Error in myReceive.generate

### ISSUE THREAD

**Issue by Thinkdiff** [blockchain/api-v1-client-node#27]
This is my code: 
`var myReceive = new Receive(xpup,callback,key);
var obj = {"secret" : "dfghg" , "incoce_id" : "1102"};
myReceive.generate(obj);`

and thiss is my error:
![asdfg](https://cloud.githubusercontent.com/assets/7890134/24078250/2b5a4558-0c7e-11e7-96aa-a654c7ea381f.PNG)

how can I fix it?

**Comment by jtormey** [comment]
Try url encoding your callback url:
```
var encodedUrl = encodeURI(callback)
```

**Comment by Thinkdiff** [comment]
I fixed that error but now I have the problem with this awful documentation!!
this is my code:
 `var obj = {"secret" : "dfghg" , "address" : "1Cf39zf9QeqjjB9hP4UKh4AH4mF2yXotzm"};
    myReceive.generate(obj);
    resp.send(myReceive);`

and worked without error. The doc said: 
_"Responds with an object containing the following properties:"_
where can I access to this response object?!!!!

**Comment by jtormey** [comment]
`Receive.generate` returns a [Promise](https://promisesaplus.com/) object, which resolves with the object described in the documentation. If you're not sure how Promises work, here's an example using `generate`:

```js
myReceive.generate(query).then(function (resultObject) {
  // the newly generated address, this is where your customer should send bitcoin
  var generatedAddress = resultObject.address;

  // the index of the newly generated address
  var index = resultObject.index;

  // the full callback url to which payment notifications will be sent
  var callbackUrl = resultObject.callback;
});
```

**Comment by Thinkdiff** [comment]
Thanx a lot 👍  but now I got this error:
![dfgnhmjkl](https://cloud.githubusercontent.com/assets/7890134/24153183/fd18f5c2-0e62-11e7-8700-a300e4ba76ee.PNG)


I copy my xpup from my blockchain account wallet > setting > address > show xpub
But I still have this error !!

**Comment by jtormey** [comment]
An xpub is not allowed to have more than 20 unused addresses in a row (this is part of the [BIP44 spec](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#address-gap-limit)). To fix this error, send bitcoin to the most recent unused address.
