### ISSUE TITLE
Help about example pushtx

### ISSUE THREAD

**Issue by Summoner2008** [blockchain/api-v1-client-node#28]
Hi team,
You can provide me one example how to use pushtx submodule. I don't find any way that use it. Thank you

**Comment by jtormey** [comment]
The pushtx submodule just takes a hex-encoded bitcoin transaction and publishes it to the bitcoin network. It doesn't help at all with creating the transaction. For that, try using [BitcoinJS](https://github.com/bitcoinjs/bitcoinjs-lib/).
