### ISSUE TITLE
Error in requiring blockchain package

### ISSUE THREAD

**Issue by Thinkdiff** [blockchain/api-v1-client-node#29]
I write my application and launched it on my VPS1 but now I`m trying run my app in new VPS and I got this error !!
How can I fix it please?

`
util.js:555
  ctor.prototype = Object.create(superCtor.prototype, {
                          ^
TypeError: Object prototype may only be an Object or null
`
![dfgdff](https://cloud.githubusercontent.com/assets/7890134/25664263/58701d4a-302f-11e7-8711-456b5bf3a3d8.PNG)

**Comment by jtormey** [comment]
What versions are you using for node and this library?

**Comment by Thinkdiff** [comment]
"blockchain.info": "^2.6.0",
"body-parser": "^1.17.1",
 "express": "^4.15.2",
"http": "0.0.0",
"request": "^2.81.0",
"socket.io": "~1.7.3",
"ws": "~2.3.1"

I can update oll of them if is nececery

**Comment by schnogz** [comment]
What version of *node* are you using for this app? 
Run `node -v` command from project root.

**Comment by Thinkdiff** [comment]
v4.2.3

**Comment by jtormey** [comment]
Are you sure this is an issue with the blockchain.info package? None of the code here or in any of our dependencies contains `Object.create(superCtor.prototype`.

Do you get the same error when running this minimal example?

```js
// ./test-blockchain-require.js
var blockchain = require('blockchain.info')
console.log(blockchain)
```
