### ISSUE TITLE
It doesn't seem possible to send using the wallet API.

### ISSUE THREAD

**Issue by kitsunde** [blockchain/api-v1-client-node#33]
According to https://github.com/blockchain/api-v1-client-node/tree/master/MyWallet#send-bitcoin `wallet.send` doesn't require a `from` field. When I run `wallet.getBalance()` it also states that I have BTC in my wallet (received days ago). However if I do:

    wallet.send("<receiving address>", 510000, {
      fee: 10000
    })

I get:

> {"error":"Insufficient funds","available":0,"needed":0.0051,"sweep_amount_satoshi":0,"sweep_fee_satoshi":0}

I've only ever received BTC once in my wallet. If I use that address in the `from` field:

    wallet.send("<receiving address>", 510000, {
      from: "<sending address>",
      fee: 10000
    })

I now get

> {"error":"Error signing and pushing transaction"}

What am I doing wrong? The service is the latest 0.24.0

**Comment by jtormey** [comment]
If the bitcoin you want to send is stored in an account, then you do need to specify the `from` parameter. For example, to send from your first account, you would put `from: 0`.

**Comment by kitsunde** [comment]
I moved on to a different wallet already so I won't check if that'll work, but you may want to specify that in the docs.

I was googling around and trying anything I could think of trying to figure out what was going on, there doesn't seem to be a mention of an index or account even being allowed, it just outright asks for a string.

I even tried bitcoin.SE: https://bitcoin.stackexchange.com/questions/53534/sending-using-blockchain-info (if you post an answer I'll accept it as true)

**Comment by jtormey** [comment]
Looks like it's buried in the [service README](https://github.com/blockchain/service-my-wallet-v3#make-payment), and was never transferred over to here. Will update the docs and close.

**Comment by kitsunde** [comment]
It would also be helpful to specify when it's not optional. Since it seems in my case, if what you're saying is true the account was required all along.

**Comment by jtormey** [comment]
Good point, done.
