### ISSUE TITLE
Refund in transactions

### ISSUE THREAD

**Issue by Thinkdiff** [blockchain/api-v1-client-node#38]
Is it possible to refund transaction amount by API in Bitcoin and this API?

**Comment by jtormey** [comment]
This API only handles receiving payments. To send bitcoin back to an address, you would have to use another API.

**Comment by BangLy** [comment]
lam cach nao nhan duoc API ma toi co the goi bit coin

**Comment by Thinkdiff** [comment]
@jtormey  Could you say the name of API that I able to refund transactions?
