### ISSUE TITLE
fromBTC it returns Internal Error

### ISSUE THREAD

**Issue by brumargues** [blockchain/api-v1-client-node#40]
Hi,
is there any limitation on the amount of requests to the public API?
So I'm getting since Monday (17/7/17), an **Internal Error** from the exchange module when requesting data over the `fromBTC` method.
Ex.
```js
blockchain.exchange
      .fromBTC(100000000, 'EUR')
      .then(data => data ? resolve(JSON.stringify(data)) : reject('No exchange available'))
      .catch(err => reject(`Blockchain API error: ${err}`));
```
I can't see any update on this library since 2 months ago. 
Is there a new version of this API?

Thank you

**Comment by jtormey** [comment]
Hi, there was a change to our server API that slightly changed a parameter. I've just updated this library, so it should work again. Thanks for letting us know!
