### ISSUE TITLE
Where are getChartData chartTypes defined?

### ISSUE THREAD

**Issue by kavinaravind** [blockchain/api-v1-client-node#43]
I was looking through this repo and 'https://blockchain.info/api/charts_api', and I was unable to find a list of all the chartTypes that are supported. I was wondering if you could provide a list of them either in your README or a link to the specified page. Thanks!

**Comment by jtormey** [comment]
I've added a list of potential values [here](https://github.com/blockchain/api-v1-client-node/tree/master/statistics#getchartdata), hopefully that helps! Later I'll look into adding these values into the codebase as well, for ease of use.

**Comment by kavinaravind** [comment]
Thanks so much! I really appreciate it. I realized later on that I could go to each displayed chart from 'https://blockchain.info/charts' and the url had the name of each chartType.

**Comment by sunit4155** [comment]
This a copyrighted A.P.I you guys could have asked permission to do what you guys did is wrong I put my heart and soul into this project only to be locked out of every single one of my accounts. To have people create a Admin account on MY Google cloud platform and start projects for profit under the pretense of non profit and do everything that is humanly and virtually possible to keep it under did you think I was stupid "I CREATED THIS" I am not a bad person but to be treated like this there will be a price.
[ISV Royalty Product List (English)(April2017)(CR) (5).docx](https://github.com/blockchain/api-v1-client-node/files/1374480/ISV.Royalty.Product.List.English.April2017.CR.5.docx)

[25306-Oracle-SM-Creative-Story-V03-RH.pdf](https://github.com/blockchain/api-v1-client-node/files/1374481/25306-Oracle-SM-Creative-Story-V03-RH.pdf)
[github-backup-utils-v2.11.0.tar.gz](https://github.com/blockchain/api-v1-client-node/files/1374482/github-backup-utils-v2.11.0.tar.gz)
[github-backup-utils-v2.11.0.tar.gz](https://github.com/blockchain/api-v1-client-node/files/1374483/github-backup-utils-v2.11.0.tar.gz)














[git hub 5.pdf](https://github.com/blockchain/api-v1-client-node/files/1374491/git.hub.5.pdf)
