### ISSUE TITLE
Is there testnet support?

### ISSUE THREAD

**Issue by raducostea** [blockchain/api-v1-client-node#46]
Does it support testnet?

**Comment by jtormey** [comment]
Not at the moment, but I think that would be an easy change to make.

**Comment by jtormey** [comment]
Testnet 5 support has been added in v2.10 for the blockexplorer, pushtx, and Socket modules.

```js
const blockexplorer = require('blockchain.info/blockexplorer').usingNetwork(5)
const { pushtx } = require('blockchain.info/pushtx').usingNetwork(5)
const mySocket = new Socket({ network: 5 })
```

**Comment by ende124** [comment]
Any chance for support for the MyWallet module?

**Comment by jtormey** [comment]
That would be a larger change, since it would involve adding testnet support for the MyWallet service. Although I can see how that would be useful to have, I'll bring it up with my team and see if we can add it.

**Comment by PandaCodes** [comment]
Looks like testnet support is unavaliable now. I got
`Error: getaddrinfo ENOTFOUND ws.testnet.blockchain.info ws.testnet.blockchain.info:443`

**Comment by jtormey** [comment]
We've recently switched over to a different testnet Blockchain (testnet3), could you pull the latest version and try with `network: 3`?
