### ISSUE TITLE
"error":"Error signing and pushing transaction"

### ISSUE THREAD

**Issue by akumbhani66** [blockchain/api-v1-client-node#53]
Service v0.26.0, Node v8.0.0, npm v5.0.0

I have the balance of 60$ in the address. now I'm trying to send 25 $ to other address in the same wallet. But unable to send. getting an error. I also have tried to change fee from 10000 to 50000 satoshis. Still getting the same error each time. :(

Also here is the log of wallet-service:

```
1515225149016 - info: blockchain.info wallet service v0.26.0 running on http://127.0.0.1:3003
(node:3723) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'priv' of undefined
(node:3723) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
1515225174845 - error: ERR_PUSHTX
(node:3723) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

Can't figure out what could be the possible reason. Any help would be appreciated.

Thanks,

**Comment by jtormey** [comment]
It doesn't seem like your issue is related to this repo, did you mean to post in https://github.com/blockchain/service-my-wallet-v3?
