### ISSUE TITLE
Transaction speed

### ISSUE THREAD

**Issue by pabx06** [blockchain/api-v1-client-node#56]
Hello after a while from using the service nicely. i have this response from API:

`
<html>
<head><title>429 Too Many Requests</title></head>
<body bgcolor="white">
<center><h1>429 Too Many Requests</h1></center>
<hr><center>nginx</center>
</body>
</html>
`

wondering if some one shed some light about api call limitation cause . and clarify speed limit on api calls.
cause i have found anything in the documentation.

i need to monitor the total sum balance for a dynamic set of address from the block chain. And wondering what are alternatives  if i could use my own copy of the blockchain ?

Thanks very much.

**Comment by jtormey** [comment]
The "Too Many Requests" limit is a global limit, so may only be an issue when we're experiencing an unusual amount of traffic. Have you continued to have this experience since posting this issue?

**Comment by pabx06** [comment]
well i am done with the API. i download the whole blockchains then parsed it using python lib. Better for doing stats on the whole block-chains than calling slow rate limited services thant doesnt precompute such things as top 100 address balances history and things like that...
