### ISSUE TITLE
How to use Blockchain.info API on TestNet ?

### ISSUE THREAD

**Issue by michealChin** [blockchain/api-v1-client-node#60]
Hi,

I have google for the whole morning about using the API that provided by Blockchain.info on TestNet, but I couldn't get any answer, can show body show me how? Thanks in advance!

**Comment by jtormey** [comment]
This library supports Testnet for the `blockexplorer`, `pushtx`, and `Socket` modules. You can find examples of how to use it in the module README.

For example, this is how you would import `blockexplorer` with Testnet3:
```js
var blockexplorer = require('blockchain.info/blockexplorer').usingNetwork(3)
```

**Comment by michealChin** [comment]
Hi, Thanks a lot!

**Comment by jtormey** [comment]
Sure!
