### ISSUE TITLE
How to use MyWallet.create ?

### ISSUE THREAD

**Issue by michealChin** [blockchain/api-v1-client-node#61]
I am using this code to create a new wallet.

       var MyWallet = require('blockchain.info/MyWallet')
	var options = { apiHost: 'http://localhost:3000' }
        var wallet = MyWallet.create('adfjladsfkjl454', '2890f5be-XXXX-XXXX-XXXX-b89af5a9XXXX', 
       options).then(function (response) {
	console.log('address:'+ response.address); 
	console.log('guid:'+ response.guid); 
       })

After I run this code, the localhost server didn't return any response. May I know what is the correct way to create a new wallet? Thanks!

**Comment by jtormey** [comment]
Are you running blockchain-wallet-service on port 3000?

**Comment by michealChin** [comment]
Yup I am running on port 3000

I run this sample code...
var options = { apiCode: 'myAPICode', apiHost: 'http://localhost:3000' }
var wallet = new MyWallet('myIdentifier', 'myPassword123', options)
wallet.getBalance().then(function (response) { console.log('My balance is %d!', response.balance); })

The server response immediately by displaying the balance on the console when I execute this code, but when I make a bit changes into MyWallet.create, the server didn't return and keep loading.

**Comment by michealChin** [comment]
Hi, today I run the same code and it can create an account without any problem so  you may close this issue now.
