### ISSUE TITLE
Fee defaults to 1130 satoshi, even when specified

### ISSUE THREAD

**Issue by almatrass** [blockchain/api-v1-client-node#68]
When no fee amount is given by me, payments default to 1130 satoshis, with a warning message of 
'It is recommended to specify a custom fee using the fee_per_byte parameter, transactions using the default 10000 satoshi fee may not confirm'. 
When I specify a fee of 10000, it sets the fee to 1130 also, with a warning message of 
'Using a static fee amount may cause large transactions to confirm slowly'.
What's wrong? Do I need to give a fee per byte for this to work properly?

**Comment by varanauskas** [comment]
@almatrass I am experiencing the same problem, did you get this resolved?
