### ISSUE TITLE
Question AddressTag API

### ISSUE THREAD

**Issue by Uter1007** [blockchain/api-v1-client-node#7]
Is there a way to retrieve Address Tags (https://blockchain.info/de/tags?form_type=1) via API ?

**Comment by jtormey** [comment]
You can see the address tag in the output of a tx (ex: https://blockchain.info/tx/f10bafaa94b21f16f0a5c16ae730933e414262a49fb77535acdf096148ea2a37?format=json), but you can’t query a specific address for it as of right now.

To get an address tag using this library, do:

```js
var blockexplorer = require('blockchain.info').blockexplorer;
var txid = 'f10bafaa94b21f16f0a5c16ae730933e414262a49fb77535acdf096148ea2a37';
function callback(err, tx) {
  var addressTag = tx.out[0].addr_tag;
  console.log(addressTag);
}
blockexplorer.getTx(txid, callback);
```
