### ISSUE TITLE
Receive Module

### ISSUE THREAD

**Issue by rudakov-bogdan** [blockchain/api-v1-client-node#70]
Hello. How long API server would be send notifications about confirmation of the transaction? 

https://github.com/blockchain/api-v1-client-node/tree/master/Receive
There is nothing about that.

https://www.blockchain.com/ru/api/api_receive
Same here.

**Comment by jtormey** [comment]
It will send notifications on every confirmation until your server responds with the string `*ok*`.

**Comment by rudakov-bogdan** [comment]
Thank you!

**Comment by jtormey** [comment]
No problem! Sounds like your issue is solved, closing.
