### ISSUE TITLE
How to decode the script from the utxo endpoint

### ISSUE THREAD

**Issue by ppoliani** [blockchain/api-v1-client-node#77]
I want to understand if there is an easy way to decode the `script` value in the utxo returned from the following api

https://testnet.blockchain.info/unspent?active=2MwcVyhWzUrS6AK8mwAZPjBfeQqtdEGgeSg|2MuJimH1ug39fd9WS96BMnk5miJbPjgqiAU.

An example of that script is 

```
"script": "a9142fe69607299d06df0bc40c0c2c0d72a4461d3e4187",
```

I wonder if there is an easy way to get the bitcoin address.

**Comment by jtormey** [comment]
Try using [BitcoinJS](https://github.com/bitcoinjs/bitcoinjs-lib), there is a section in the library for handling bitcoin scripts. Example:

```js
const Bitcoin = require('bitcoinjs-lib')

const script = Buffer.from('a9142fe69607299d06df0bc40c0c2c0d72a4461d3e4187', 'hex')
const scriptAsm = Bitcoin.script.toASM(Bitcoin.script.decompile())

// scriptAsm => 'OP_HASH160 2fe69607299d06df0bc40c0c2c0d72a4461d3e41 OP_EQUAL'
```

That script only gives you the "hash160" of `2MwcVyhWzUrS6AK8mwAZPjBfeQqtdEGgeSg`, not the bitcoin address itself. You can see the hash160 of an address [on our explorer](https://testnet.blockchain.info/address/2MwcVyhWzUrS6AK8mwAZPjBfeQqtdEGgeSg), under "Summary".

Hope that helps!

**Comment by ppoliani** [comment]
@jtormey thanks!
