### ISSUE TITLE
How to reused outbound connection with require('blockchain.info/blockexplorer')?

### ISSUE THREAD

**Issue by michealChin** [blockchain/api-v1-client-node#81]
Hi,

I host my Node.js server at Azure, recently I encounter an issue which hits the outbound connection limit at Azure. 

Azure suggest that:
For Node.js applications making outbound HTTP/HTTPS calls, configure keep-alives so that outbound connections are reused.

I would like to know how to keep-alives with 'blockchain.info/blockexplorer connection so that I can reduce the number of outbound connections.

Please advise, Thanks in Advance!

Here is the method to query the balance of and address from 'blockchain.info/blockexplorer.

```
exports.GetBalance = function (mainStr, sock, testNet, encryp) {
   
    var options = { apiCode: mainStr.apiCode }
    var blockexplorer = require('blockchain.info/blockexplorer');
    if (testNet) {
        blockexplorer = require('blockchain.info/blockexplorer').usingNetwork(networkID);
    }
    blockexplorer.getBalance(address, options).then(function (response) {
        if (Debug)
            console.log(response);
        var myObj = { "CoinName": "bitcoin", "Command": "GetBalance", "confirm": response[address].final_balance };
        var myJSON = JSON.stringify(myObj);
        if (websocket)
            sock.send(myJSON + DELIM);
        else
            sock.write(myJSON + DELIM);
    }).catch((err) => {
        var myObj = { "CoinName": "bitcoin", "Command": "GetBalance", "confirm": 0 };
        var myJSON = JSON.stringify(myObj);
        if (websocket)
            sock.send(myJSON + DELIM);
        else
            sock.write(myJSON + DELIM);
    });
}
```

**Comment by michealChin** [comment]
Hi, 

May I know where can I configure the keepalive setting?

**Comment by jtormey** [comment]
That's not an option in this library, you would have to implement it yourself in Node using our HTTP API directly. As for how to do that, I'm not sure.

**Comment by michealChin** [comment]
Hi,

Thank you jtormey!
