### ISSUE TITLE
The api endpoint for pushTx

### ISSUE THREAD

**Issue by michealChin** [blockchain/api-v1-client-node#82]
Hi,

I host my server at Azure and recently hit the outbound connection limit, so I plan to access the API endpoint directly and using agentkeepalive to maintain the connection without have to reopen a new connection with blockchain.info.   Following is my existing code:

```
var pushtx = require('blockchain.info/pushtx').usingNetwork(networkID);
            pushtx.pushtx(txSerialized, options).then(function (response) {
                if (Debug) {
                    console.log(response);
                }
            });
```

I would like to know where is the API endpoint for the pushtx? Here is my code, but it always return with error page 404. Can someone show me the correct way?

```
const keepaliveAgentBitcoinBlockchainInfoTest = new HttpsAgent();
//https://test-insight.bitpay.com/api/addr/n2tXWrsXZwmcF9kEMj2MRhrmh89BowkB63/utxo
const optionsBitTest = {
    host: 'testnet.blockchain.info',
    port: 443,
    path: '/',
    method: 'GET',
    body: '',
    agent: keepaliveAgentBitcoinBlockchainInfoTest,
};
exports.Test = function (options) {
  var txSerialize = '01000000015818e695d25684a1b2e4cdd612eb4eb2c85eba7002a3bbdc73908a754bdbd9e1010000006b4830450221008da09f02274d5312f30575a948c5f4bf2dcfebdf7bfa45a2480742b3772d212f022051769082a950b5ad05d416227addc502eaf415b141bef7f1435d7fbac42702d40121039127baac8f60e95012e435b3f75a124fb3da35e9cdf3bc8ecaaa6281bd9ebe12ffffffff0210270000000000001976a91498e2d374949a014c4caa27a1006768ae80bad2a188ac60510000000000001976a914ad9e65bf015c9c18d45286a5d072f41eef5ae58788ac00000000';

    const https = require('https');
    options.path = '/pushtx/'+txSerialize;
    options.method = 'POST';

    const req = https.request(options, res => {
        console.log('localPort: ' + res.client.localPort);
        res.setEncoding('utf8');
        //res.on('data', chunk => {
        //    console.log('BODY: ' + chunk);
        //});
        var body = '';
        res.on('data', function (chunk) {
            body += chunk;
        });
        res.on('end', function () {
            //console.log('BODY: ' + body);
        });
    });
}
```

**Comment by jtormey** [comment]
Looks like the issue might be that you're using a relative path (`/pushtx`), instead try using the full path. For mainnet it's https://blockchain.info/pushtx and for testnet it's https://testnet.blockchain.info/pushtx. Hope that helps!

**Comment by michealChin** [comment]
Hi,

I try the following but it return Error 404.

https://testnet.blockchain.info/pushtx/01000000015818e695d25684a1b2e4cdd612eb4eb2c85eba7002a3bbdc73908a754bdbd9e1010000006b4830450221008da09f02274d5312f30575a948c5f4bf2dcfebdf7bfa45a2480742b3772d212f022051769082a950b5ad05d416227addc502eaf415b141bef7f1435d7fbac42702d40121039127baac8f60e95012e435b3f75a124fb3da35e9cdf3bc8ecaaa6281bd9ebe12ffffffff0210270000000000001976a91498e2d374949a014c4caa27a1006768ae80bad2a188ac60510000000000001976a914ad9e65bf015c9c18d45286a5d072f41eef5ae58788ac00000000

**Comment by jtormey** [comment]
To submit a transaction, you must submit a POST request.

Here is an example cURL:

```sh
curl 'https://blockchain.info/pushtx' --data 'tx=$YOUR_TX_HEX'
```

Here is an example using Node.js:

```js
var qs = require("querystring");
var http = require("https");

var options = {
  "method": "POST",
  "hostname": "blockchain.info",
  "port": null,
  "path": "/pushtx",
  "headers": {
    "content-type": "application/x-www-form-urlencoded",
    "cache-control": "no-cache"
  }
};

var req = http.request(options, function (res) {
  var chunks = [];

  res.on("data", function (chunk) {
    chunks.push(chunk);
  });

  res.on("end", function () {
    var body = Buffer.concat(chunks);
    console.log(body.toString());
  });
});

req.write(qs.stringify({ tx: YOUR_TX_HEX }));
req.end();
```

**Comment by michealChin** [comment]
Hi,

Regarding to the Node.js example, may I know where is the variable that store the sign transaction?

**Comment by jtormey** [comment]
In the example, `YOUR_TX_HEX` is meant to reference the signed transaction hex of the transaction you want to send. In your case, you would have

```js
var qs = require("querystring");
var http = require("https");

// From your example
var myTxHex = "01000000015818e695d25684a1b2e4cdd612eb4eb2c85eba7002a3bbdc73908a754bdbd9e1010000006b4830450221008da09f02274d5312f30575a948c5f4bf2dcfebdf7bfa45a2480742b3772d212f022051769082a950b5ad05d416227addc502eaf415b141bef7f1435d7fbac42702d40121039127baac8f60e95012e435b3f75a124fb3da35e9cdf3bc8ecaaa6281bd9ebe12ffffffff0210270000000000001976a91498e2d374949a014c4caa27a1006768ae80bad2a188ac60510000000000001976a914ad9e65bf015c9c18d45286a5d072f41eef5ae58788ac00000000";

/* code omitted for clarity */

req.write(qs.stringify({ tx: myTxHex }));
req.end()
```

**Comment by michealChin** [comment]
Hi Jtormey,

Regarding to the pushtx API example above, How do I submit the api key to avoid Request Limits?

**Comment by jtormey** [comment]
You can add it in the pushtx options:

```js
pushtx.pushtx(transaction, { apiCode: myApiCode })
```

**Comment by michealChin** [comment]
Hi @jtormey

 I mean how to submit apicode together with the HTTPS POST request?

**Comment by jtormey** [comment]
Submit it as part of the POST body, as `api_code`

**Comment by michealChin** [comment]
OK, Thanks!

**Comment by ekkis** [comment]
> for testnet it's https://testnet.blockchain.info/pushtx

that link just redirects to https://www.blockchain.com/btc/pushtx which looks like a mainnet to me.  any idea what the correct url might be?
