### ISSUE TITLE
Would the other api like https://api.blockchain.info/v2/receive/balance_update be supported on the testnet ?

### ISSUE THREAD

**Issue by woshidama323** [blockchain/api-v1-client-node#83]
_Originally posted by @jtormey in https://github.com/blockchain/api-v1-client-node/issues/60#issuecomment-377273472_

**Comment by woshidama323** [comment]
Did i post a wrong place for asking for help ?

**Comment by jtormey** [comment]
Unfortunately we don't have a Testnet version of this API at the moment.
