### ISSUE TITLE
URL address in requesting an API key

### ISSUE THREAD

**Issue by genisgetman** [blockchain/api-v1-client-node#86]
Hello! Is url in requesting for receive an API key means url for GET/POST requests from blockchain.info or is it just main url of website/application?
If yes, definition of the url for requests in the below function?
```
var Receive = require('blockchain.info/Receive')
var myReceive = new Receive(xpub, callback, key, options)
```

**Comment by jtormey** [comment]
It should be a URL pointing us to the site or service that will use the API, so that we can verify it exists. If this does not apply to you, just enter the domain of the callback URL you will be using.
