### ISSUE TITLE
testnet.blockchain.info network definition

### ISSUE THREAD

**Issue by genisgetman** [blockchain/api-v1-client-node#87]
Hi, could you give me please the object that definiting the testnet network?
for example: 
```
let network = {
  messagePrefix: '\x18Bitcoin Signed Message:\n',
  bech32: '_',
  bip32: {
    public: 0x,
    private: 0x
  },
  pubKeyHash: 0x,
  scriptHash: 0x,
  wif: 0x
}
```

**Comment by genisgetman** [comment]
It seems to be that what i need but it is not.
I need to take exactly definition of blockchain.info testnet network.
For example: 
I try to create some address by bitcoinjs-lib  with this options then i get the string error from blockchain.info API when i try to get the balance of this address
Error is "Invalid Bitcoin Address"
This error indicate that address created on another network

**Comment by jtormey** [comment]
Hmm how exactly are you generating it? I did the following:

*Generate testnet address*

```js
> Bitcoin.ECPair.makeRandom({ network: Bitcoin.networks.testnet }).getAddress()
'mjJNpf8Yq1Ghy3ZoGoz4xei7ou19Uopa6x'
```

*Using this library, look up the address info*

```js
const blockexplorer = require('blockchain.info/blockexplorer').usingNetwork(3)
blockexplorer.getAddress('mjJNpf8Yq1Ghy3ZoGoz4xei7ou19Uopa6x').then(console.log)
```

This address is also valid on our testnet3 block explorer:
https://testnet.blockchain.info/address/mjJNpf8Yq1Ghy3ZoGoz4xei7ou19Uopa6x

**Comment by genisgetman** [comment]
Oh! Your example is works well. My problem was I manually defined the network from object. Thanks!
