### ISSUE TITLE
Can't query a block on testnet

### ISSUE THREAD

**Issue by DVH1990** [blockchain/api-v1-client-node#88]
Hi folks,

```
var blockexplorer = require('blockchain.info/blockexplorer').usingNetwork(3)
console.log(blockexplorer.getBlock('1454671'))

```

I'm calling getBlock on testnet with block height and I always get "Block not found". When querying with block hash it does seem to work. Querying on the mainnet with block height does seem to work though.

Is it possible that getBlock is not supported for block height on testnet?

**Comment by jtormey** [comment]
That's strange, when I do the same I get a result:

```js
> let blockexplorer = require('blockchain.info/blockexplorer').usingNetwork(3)
> blockexplorer.getBlock(1454671).then(console.log)
> { hash: '000000002c2ae18e08cc73b78737807e4ac3836f5e12859270d1c6a2a68dba4f',
  ver: 2,
  prev_block: '000000000f046107af97da0b50ef6a9accac5d0529193df9349122630ce6a78c',
  ... }
```

This is a pretty recent block, it's possible that our testnet explorer was slightly behind at the time you tried. Are you still consistently seeing "Block not found"? If so I can check with our platform team to confirm if there are any issues.

**Comment by DVH1990** [comment]
Looks like there was a problem on our part, this is not an issue anymore, thanks!
