### ISSUE TITLE
Getting false info

### ISSUE THREAD

**Issue by DVH1990** [blockchain/api-v1-client-node#89]
Hi folks

I'm working on the testnet with the following address: mkfZwTdCJBbmwJGqGneEy6psoWyBik2H9d

I'm using blockchain.info explorer to get unspent outputs and balance info - but it seems like the info I'm getting is out of date, as if the last transaction that I ran didn't register. In particular:
- My query returns n_tx as being 42. When going to the actual blockchain explorer that number is 43 (which is what it should be)
- Unspent outputs are different

Here's the address on the explorer with the correct info: https://www.blockchain.com/btctest/address/mkfZwTdCJBbmwJGqGneEy6psoWyBik2H9d

What's going on? Why am I getting outdated info from the API?

Thanks!

**Comment by PhillipMwaniki** [comment]
Yeah, I'm having a similar problem on this. Did you get a solution ?

**Comment by DVH1990** [comment]
Nope, it's still the same issue. Through the API I get 42 txs and relevant unspent outputs. The actual info is not the same.

**Comment by jtormey** [comment]
It seems our testnet explorer is behind right now. I'll post an update in #93 once it's caught up.

**Comment by jtormey** [comment]
Our block explorer is caught up now, so this should be fixed. Mind if I close?

**Comment by DVH1990** [comment]
Yes this seems fine, thanks
