### ISSUE TITLE
No addresses transactions are returned when we call getMultiAddress on testnet

### ISSUE THREAD

**Issue by ppoliani** [blockchain/api-v1-client-node#90]
Last week `getMultiAddress`stopped returning transaction for a list of addresses. I checked the addresses on the explorer and they all are involved in transactions. It there any change we should be aware of? 

Has the URL been changed and not been updated in this package?

**Comment by jtormey** [comment]
Hey! Happy to look into this. Do you have an example address list I could reference?

**Comment by ppoliani** [comment]
Hi @jtormey,

Following are addresses that, as you can see in the explorer, do have some transactions.

https://www.blockchain.com/btctest/address/2MwRj8bFFCLzTm2ngSQCXkEGaiUf68229f5

https://www.blockchain.com/btctest/address/2MwjiQatqwcEsHZdNucvLn2MyKYJoBNPd4h

**Comment by ppoliani** [comment]
@jtormey have we got any updates on this one? Is there anything we can help you with?

**Comment by jtormey** [comment]
Our testnet explorer is behind right now, we're working on catching it up. See #93 for updates

**Comment by jtormey** [comment]
Looks like this is resolved, mind if I close?

**Comment by ppoliani** [comment]
@jtormey thanks, mate! Looks good now.
