### ISSUE TITLE
No data for testnet

### ISSUE THREAD

**Issue by ekkis** [blockchain/api-v1-client-node#93]
I have the following simple code:
```javascript
var Socket = require('blockchain.info/Socket');
console.log(Socket.wsUrlForNetwork(3));

var sck = new Socket({network: 3});
sck.onClose(res => console.log('SOCKET CLOSED'));
sck.onTransaction(res => console.log(res));
```
which prints:
> wss://ws.blockchain.info/testnet3/inv

and nothing evermore.  by comparison, with `network: 0` I get the data I expect.  is it the service that's unavailable, or the module that's broken?

**Comment by angelosuinan** [comment]
It is the service that is down

> wss://ws.blockchain.info/testnet3/inv

You can try to send messages using http://websocket.org/echo.html with https://www.blockchain.com/api/api_websocket. It seems that `{"op":"ping"}` is the only one working

**Comment by jtormey** [comment]
Our testnet explorer is behind right now, we're currently working on catching up to the current block height. Until then our testnet API will miss realtime data. I'll post here when it's fixed 👍

**Comment by jtormey** [comment]
Ok, all caught up! Testnet APIs should be working as expected now 🙂

**Comment by anjalialance** [comment]
Thank You Man.! :)
